export {default as Home} from './Home/Home'
export {default as UmrahPrograms} from './UmrahPrograms/UmrahPrograms'
export {default as HajjPrograms} from './HajjPrograms/HajjPrograms'
export {default as Hotel} from './Hotel/Hotel'
export {default as Transport} from './Transport/Transport'
export {default as RegisterProgramUmrah} from './PagesRegister/RegisterProgramUmrah/RegisterProgramUmrah'
export {default as RegisterProgramHajj} from './PagesRegister/RegisterProgramHajj/RegisterProgramHajj'
export {default as RegisterProgramSpecial} from './PagesRegister/RegisterProgramSpecial/RegisterProgramSpecial'