export {default as Header} from "./Header/Header";
export {default as Footer}  from "./Footer/Footer";
export {default as SectionMain}  from "./SectionMain/SectionMain";
export {default as UmrahPrograms} from "./UmrahPrograms/UmrahPrograms";
export {default as HajjPrograms} from "./HajjPrograms/HajjPrograms";
export {default as Hotel} from "./Hotel/Hotel"
export {default as About} from "./About/About"
export {default as SectionTransport} from "./SectionTransport/SectionTransport"
export {default as PlacesInMacca} from "./PlacesInMacca/PlacesInMacca"
export {default as PlacesInMadena} from "./PlacesInMadena/PlacesInMadena"
