export {default as CardUmrahProgram} from './CardUmrahProgram/CardUmrahProgram'
export {default as CardHotel} from './CardHotel/CardHotel'
export {default as HotelInUmrahProgram} from './HotelInUmrahProgram/HotelInUmrahProgram'
export {default as CardHajj} from './CardHajj/CardHajj'
export {default as SliderHotel} from './SliderHotel/SliderHotel'